# Plugins
plugins:
  - jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ["/automation/", "README.md", "LICENSE.txt", "CNAME"]

# Site Settings
title: "2020 CLIMAS | 臺大中文資管大氣聯合迎新宿營"
email: "brian.lxchen@gmail.com"
description: "2020 CLIMAS 臺大中文 x 臺大資管 x 臺大大氣聯合迎新宿營將在民國109年9月11日到13日於台中流星花園舉辦。恭喜各位B09的學弟妹進入臺大這個大家庭。快來報名參加這次由臺大三系共同合辦三天兩夜的聯合迎新宿營，在開學前來場美麗的邂逅（認識大家、交朋友、問學長姐問題）吧！"
baseurl: ""
url: "https://climas.now.sh"
# permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-162829284-5"
siteVerification: "oYnWS4rMeEdlsqDX135peKCdqXc8RyUErIy"

# Organizer Info
organizerName: "CLIMAS"
organizerAlternateName: "2020 CLIMAS Camp"
organizerDescription: "臺大中文 x 臺大資管 x 臺大大氣聯合迎新宿營 籌辦團隊"
organizerEmail: "2020climas@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://climas.now.sh/"

# Head
metaKeywords: "event, CLIMAS, 臺大, 宿營, 台大, 臺大中文 x 臺大資管 x 臺大大氣聯合宿營, NTU, IM, AS, CL, 國立台灣大學, 國立臺灣大學, 資管, 中文, 大氣, 聯合宿營, 迎新宿營, 迎新, 資訊管理學系迎新, 資訊管理學系宿營, 大氣科學系宿營, 大氣科學系迎新, 中國文學系宿營, 中國文學系迎新"
# socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://climas.now.sh/2020/07/11/if-youd-like-to-contribute-zh_tw/"
c4sponsorsUrl: "/how-to-sponsor/"
c4sponsorsInd: "/how-to-sponsor/"
c4sponsorsList: "/sponsors/"

# Navigation
navigationLinks:
  - { permalink: "/", text: "首頁" }
  - { permalink: "/schedule/", text: "活動流程" }
  - { permalink: "/team/", text: "認識團隊" }
  - { permalink: "/blog/", text: "最新消息" }
  - { permalink: "/downloads/", text: "下載區" }
  - { permalink: "/faq/", text: "FAQ" }
bottomNavigationLinks:
  - { link: "https://climas.now.sh/#tickets", text: "馬上報名" }
rightNavigationButtons:
  - { link: "https://climas.now.sh/#tickets", text: "馬上報名" }

# Hero Block
heroImage: "hero.png"
heroTitle: "2020 CLIMAS"
eventDate: "Sept. 11 - 13, 2020"
typeoutTextValues: '"", "國立臺灣大學", "中國文學系", "資訊管理學系", "大氣科學系", "聯合迎新宿營"'
typeoutFallback: "臺大中文 x 臺大資管 x 臺大大氣聯合迎新宿營"
heroButtons:
  - { permalink: "/blog/", text: "最新消息" }
  - { permalink: "/#tickets", text: "馬上報名" }
  - { permalink: "/how-to-sponsor/", text: "我想贊助" }

# About Block
aboutTitle: "營隊簡介"
aboutBlock:
  - {
      title: "提前認識系上同學與學長姊！",
      text: "想提前認識系上同學與學長姊，為校園生活譜下美好序曲嗎？<br>
        想要認識不同系所的人，讓生活圈更加廣泛嗎？<br>
        想知道選課攻略、系上球隊、多樣社團、校園生活等第一手資訊嗎？<br>
        那就一定不能錯過這次的迎新宿營！",
    }
  - {
      title: "CLIMAX (s)，高峰點",
      # image: "Mount-Everest.jpg",
      text:
        "卸下了背負十餘年的重擔，在踏入校園的前夕，你是否對於未知的大學生活感到忐忑不安？<br>
        是否覺得眼前道路彷彿幽深無盡的叢林？<br>
        作為高中生涯結束進入大學的儀式，在這三天兩夜的迎新宿營中，我們希望能夠作為你們大學生活的明燈，創造人生另一個 <code>Climax</code>！
        ",
    }
  - {
      title: "臺大生存攻略？",
      text:
        "透過精心設計的各種活動與遊戲，拉近彼此距離；同時藉由學長姐QA時間，成功獲得臺大生存攻略。
        你，千萬不能錯過。",
    }

# Statistic Block
statisticBlockImage: "statistic.png"
statisticBlock:
  - {
      count: "50",
      specialCharacter: "+",
      info: "學員",
      detail: "來自全台（世界？）各地的 Elites！",
    }
  - {
      count: "600",
      specialCharacter: "+",
      info: "小時",
      detail: "學長姐們的精心策劃",
    }
  - {
      count: "3",
      specialCharacter: "",
      info: "系所",
      detail: "中文、資管、大氣三系組成多方認識系上、外系朋朋",
    }
  - {
      count: "3",
      specialCharacter: "",
      info: "天",
      detail: "讓你收穫滿滿的營隊",
    }

# Latest News Block
latestNewsTitle: "最新消息"

# Rockstar Speakers Block
rockstarSpeakersTitle: "加入我們"
rockstarSpeakersImage: "rockstar.png"
rockstarSpeakersCount: 4
rockstarSpeakersButtonText1: "查看我們團隊"
# rockstarSpeakersButtonText2: "WE ROCK 成員"

# Location Block
locationBlockTitle: "地點連結"
eventLocationName: "Conference Hall"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "22 Teatral'na St"
eventAddressLocality: "Lviv"
eventAddressLocalityRegion: "Lvivska"
eventPostalCode: "79000"
eventAddressCountry: "Ukraine"
eventStartTime: "2014-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "49.843237, 24.028751"
mapCenterCoordinates: "49.842537, 24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "場地介紹"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "<strong>台中流星花園</strong>"
venueFeatures:
  [
    "<strong>地址</strong>：台中市豐原區水源路坪頂巷8號",
    "<strong>電話</strong>：04-25151456",
    '<a href="http://www.glp.com.tw">點我查看台中流星花園官網！</a>',
  ]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "主辦團隊"
partnersTitle: "贊助夥伴"
partnersC4sponsorsButton: "我想贊助！"
partnersC4sponsorsLink: "完整贊助名單"
partnersC4sponsorsInd: "小額贊助專區"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "報名連結"
ticketsInfoTitle: "報名資訊"
ticketsInfo: '報名之後，顯示以下：<br><br>
            <svg width="60px" height="60px" viewBox="0 0 60 60" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <g id="Thank-You" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <g id="thanks" transform="translate(-690.000000, -263.000000)">
                        <g id="Group" transform="translate(692.000000, 265.000000)">
                            <circle id="Oval-Copy" stroke="#34D183" stroke-width="3" fill="#FFFFFF" cx="28" cy="28" r="28"></circle>
                            <g id="check-small" transform="translate(18.000000, 21.000000)" fill="#34D183" fill-rule="nonzero">
                                <path d="M5.85714286,17 C5.38571429,17 5.07142857,16.83 4.75714286,16.49 L-1.52857143,9.69 C-2.15714286,9.01 -2.15714286,7.99 -1.52857143,7.31 C-0.9,6.63 0.0428571429,6.63 0.671428571,7.31 L5.85714286,12.92 L17.3285714,0.51 C17.9571429,-0.17 18.9,-0.17 19.5285714,0.51 C20.1571429,1.19 20.1571429,2.21 19.5285714,2.89 L6.95714286,16.49 C6.64285714,16.83 6.32857143,17 5.85714286,17 Z" id="Shape"></path>
                            </g>
                        </g>
                    </g>
                </g>
            </svg><br>
            <h6>Thank You</h6>感謝報名 2020 CLIMAS 臺大中文資管大氣聯合迎新宿營<br><br>
            才代表報名完成。若報名之後十五分鐘內沒有收到 Email 通知，請<a href="mailto:2020climas@gmail.com">聯繫我們</a>或相關承辦人員！'
ticketsOffers:
  - name: "報名連結"
    price: "3,700 "
    priceCurrency: "NTD"
    ticketsNumber: "100"
    ribbon: "豐原集合"
    featured: true
    permalink: "/application/3700/"
    buyButtonText: "點我進入報名頁面"
    ticketContentList: ["去程自行前往豐原火車站", "繳費截止日期為：2020/9/4"]
    validFrom: "2020-08-01T00:00"
    validThrough: "2020-08-30T23:59"
    disabled: true


  - name: "報名連結"
    price: "4,000 "
    priceCurrency: "NTD"
    ticketsNumber: "100"
    ribbon: "臺大集合"
    permalink: "/application/4000/"
    buyButtonLink: "#"
    buyButtonText: "點我進入報名頁面"
    ticketContentList: ["去程於台北和工人一起搭遊覽車前往流星花園", "繳費截止日期為：2020/9/4"]
    validFrom: "2020-08-01T00:00"
    validThrough: "2020-08-30T23:59"
    disabled: true

ticketsInfoText:
  - name: "報名資格"
    detail: "全體臺大中文、大氣及資管系大一新生"
  - name: "活動地點"
    detail: "台中流星花園（台中市豐原區水源路坪頂巷8號）"
  - name: "活動日期"
    detail: 2020・9/11（五）- 9/13（日）
  - name: "報名截止日期"
    detail: "2020・8/30（日）"
  - name: "營隊費用"
    detail1: "去程自行前往豐原火車站： <mark>新台幣 3,700 元整</mark>"
    detail2: "去程於台北和學長姐一起搭遊覽車前往流星花園： <mark>新台幣 4,000 元整</mark>"
  - name: "繳費資訊"
    info: "請將報名費用匯款至以下帳戶（繳費截止日期為：<mark>2020/9/4</mark>）"
    accountPrompt: "匯款帳戶"
    accountID: "062-49-7915498-1"
    accountNamePrompt: "戶名"
    accountName: "范傑翔"
    bankPrompt: "銀行"
    bankName: "808-玉山銀行"
  - name: "注意事項"
    detail: '報名完成後，請填妥新生家長同意書於活動開始時帶至現場繳交。若有需要提前離營，請一併填寫提前離營切結書且於活動開始時帶至現場繳交。宿營相關文件請參閱<a href="/downloads/">下載區</a>。'

# Footer
socialLinks:
  - { link: "#", icon: "facebook" }
  - { link: "https://github.com/icheft/2020climas", icon: "github" }

footerBlocks:
  - title: "合作夥伴"
    links:
      - { permalink: "/sponsors/", text: "完整贊助名單" }
      - { permalink: "/how-to-sponsor/", text: "贊助說明文件" }
      - { permalink: "#", text: "網站資訊提供" }
      
  - title: "聯絡我們"
    links:
      - { link: "tel:+886989350258", text: "資訊管理學系窗口：郭子麟" }
      - { link: "tel:+886910432100", text: "大氣科學系窗口：陶昱丞" }
      - { link: "tel:+886984200546", text: "中國文學系窗口：黃研倫" }
      - { link: "mailto:2020climas@gmail.com", text: "2020 CLIMAS 臺大中文資管大氣聯合迎新宿營 官方信箱" }
  - title: "常用連結"
    links:
      - { link: "https://ceiba.ntu.edu.tw/student/index.php", text: "CEIBA" }
      - { link: "https://cool.ntu.edu.tw/", text: "NTU Cool" }
      - { link: "https://pdogs.ntu.im/judge/", text: "PDOGS" }
      - { link: "https://if192.aca.ntu.edu.tw/index.php", text: "臺大選課系統" }
      - {
          link: "https://nol.ntu.edu.tw/nol/guest/index.php",
          text: "臺大課程網",
        }
      - {
          link: "https://web4.cc.ntu.edu.tw/p/s/login3/p1.php",
          text: "臺大帳號設定",
        }
      - {
          link: "http://www.cc.ntu.edu.tw/chinese/services/servicesqa.asp",
          text: "計中",
        }
  - title: "站內重要連結"
    links:
      - { permalink: "/faq/", text: "FAQ 常見問題錦囊" }
      - { permalink: "/downloads/", text: "下載區" }
      - { permalink: "/how-to-sponsor/", text: "如何贊助本活動" }
      - { permalink: "/#tickets", text: "報名入口" }

# Blog
blogTitle: "最新消息"
blogCommentsEnabled: true
discusShortName: "climas"

# Speakers List Block
showSessions: false
rockstarName: "WE ROCK"

# Team Block
teamBlockTitle: "關於我們"
aboutUs: "CLIMAS．臺大中文資管大氣聯合迎新宿營 籌備團隊"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction.png"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
  - {
      title: "From the Airport",
      information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.',
    }
  - {
      title: "Public Transit",
      information: "Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.",
    }
  - {
      title: "Hotels",
      information: "Lviv has lots of great hotels and hostels. More information will be available later.",
    }
directionDetailsWideCards:
  - title: "Questions?"
    subCards:
      - title: "Hotels"
        links:
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "InterContinental",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "The Hotel Rex",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Westin Market Street",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Hotel Adagio",
            }
      - title: "Registration"
        links:
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "InterContinental",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "The Hotel Rex",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Westin Market Street",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Hotel Adagio",
            }
      - title: "Attendance Details"
        links:
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "InterContinental",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "The Hotel Rex",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Westin Market Street",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Hotel Adagio",
            }

downloadDetailsImage: "direction.png"
downloadDetailsTitle: "一些你可能需要的文件都在這"
downloadDetailsCards:
  - {
      title: "行前通知書",
      information: '上營前請記得要看！如果你有需要隊輔協助，請你不要猶豫，直接聯絡他們。<br><a href="/assets/2020行前通知書.pdf" class="btn btn-warning waves-effect waves-light waves-float" style="margin-top: 10px; color: #fff;">點我下載</a>',
    }
  - {
      title: "新生家長同意書",
      information: '這份文件很重要！上營一定要帶！<br><a href="/assets/2020新生家長同意書.pdf" class="btn btn-warning waves-effect waves-light waves-float" style="margin-top: 10px; color: #fff;">點我下載</a>',
    }
  - {
      title: "提前離營切結書",
      information: '如果你有需要提前離開本次營隊，請你務必將此切結書下載並列印。簽名後於活動當天交給隊輔。 <br><a href="/assets/2020提前離營切結書.pdf" class="btn btn-warning waves-effect waves-light waves-float" style="margin-top: 10px; color: #fff;">點我下載</a>',
    }
  - {
      title: "中途離營切結書",
      information: '如果需要中途離營，請你務必將此切結書下載並列印。簽名後於活動當天交給隊輔。<br><a href="/assets/2020中途離營切結書.pdf" class="btn btn-warning waves-effect waves-light waves-float" style="margin-top: 10px; color: #fff;">點我下載</a>',
    }
  - {
      title: "營手冊",
      information: "營手冊上營時不會發，我們走一個環保路線♻️所以，如果你堅持看紙本的話，請記得自己印下來！<br><br>在這裏，我們推薦你下載存在你最容易看到的位子，抑或是營隊當天，開啟本頁面瀏覽，數位化的時代，用電子檔案才是王道呀哈哈！<br><a href='https://drive.google.com/file/d/1YtzSFP6n_14myJAtGZWiAVv5nq9kS3g9/view' class='btn btn-warning waves-effect waves-light waves-float' style='margin-top: 10px; color: #fff;'>點此瀏覽</a>",
    }
downloadDetailsWideCards:
  - title: "Questions?"
    subCards:
      - title: "Hotels"
        links:
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "InterContinental",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "The Hotel Rex",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Westin Market Street",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Hotel Adagio",
            }
      - title: "Registration"
        links:
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "InterContinental",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "The Hotel Rex",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Westin Market Street",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Hotel Adagio",
            }
      - title: "Attendance Details"
        links:
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "InterContinental",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "The Hotel Rex",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Westin Market Street",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Hotel Adagio",
            }

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
  - {
      title: "Android Wear",
      image: "hackathon-0.png",
      details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!",
    }
  - {
      title: "Google Glass",
      image: "hackathon-1.png",
      details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience.",
    }
  - {
      title: "Polymer",
      image: "hackathon-2.png",
      details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time.",
    }

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
  - { title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360" }
  - {
      title: "1nd Place",
      image: "prize-1.png",
      info: "Nexus 5 with pre-installed Android L",
    }
  - { title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast" }

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"

theme: jekyll-theme-cayman
