# Plugins
plugins:
  - jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ["/automation/", "README.md", "LICENSE.txt", "CNAME"]

# Site Settings
title: "2020 CLIMAS | ä¸­æ–‡è³‡ç®¡å¤§æ°£è¯åˆå®¿ç‡Ÿ"
email: "brian.lxchen@gmail.com"
description: "2020 CLIMAS CAMP is welcoming all freshmen majoring in CL, IM, and AS to embark on a special 3-day journey with seniors."
# baseurl: "/climas"
url: "https://climas.now.sh"
# permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-162829284-5"
siteVerification: "oYnWS4rMeEdlsqDX135peKCdqXc8RyUErIy"

# Organizer Info
organizerName: "CLIMAS"
organizerAlternateName: "2020 CLIMAS Camp"
organizerDescription: "Student group ready for 2020 CLIMAS Camp."
organizerEmail: "imsa@ntu.im"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://climas.now.sh/"

# Head
metaKeywords: "event, å®¿ç‡Ÿ, å°å¤§, NTU, IM, AS, CL"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://climas.now.sh/2020/07/11/if-youd-like-to-contribute-zh_tw/"
c4sponsorsUrl: "mailto:brian.lxchen@gmail.com"

# Navigation
navigationLinks:
  - { permalink: "/", text: "é¦–é " }
  - { permalink: "/schedule/", text: "æ´»å‹•æµç¨‹" }
  - { permalink: "/team/", text: "èªè­˜åœ˜éšŠ" }
  - { permalink: "/blog/", text: "æœ€æ–°æ¶ˆæ¯" }
  - { permalink: "/downloads/", text: "ä¸‹è¼‰å€" }
  - { permalink: "/faq/", text: "FAQ" }
bottomNavigationLinks:
  - { link: "https://climas.now.sh/#tickets", text: "é¦¬ä¸Šå ±å" }
rightNavigationButtons:
  - { link: "https://climas.now.sh/#tickets", text: "é¦¬ä¸Šå ±å" }

# Hero Block
heroImage: "hero.jpg"
heroTitle: "2020 CLIMAS"
eventDate: "Sept. 11 - 13, 2020"
typeoutTextValues: '"", "ä¸­åœ‹æ–‡å­¸ç³»", "è³‡è¨Šç®¡ç†å­¸ç³»", "å¤§æ°£ç§‘å­¸ç³»", "è¯åˆå®¿ç‡Ÿ"'
typeoutFallback: "ä¸­æ–‡ x è³‡ç®¡ x å¤§æ°£è¯åˆå®¿ç‡Ÿ"
heroButtons:
  - { permalink: "/#tickets", text: "é¦¬ä¸Šå ±å" }
  - { link: "#", text: "å‰å¾€ç²‰å°ˆ" }

# About Block
aboutTitle: "ç‡ŸéšŠç°¡ä»‹"
aboutBlock:
  - {
      title: "æå‰èªè­˜ç³»ä¸ŠåŒå­¸èˆ‡å­¸é•·å§Šï¼",
      text: "æƒ³æå‰èªè­˜ç³»ä¸ŠåŒå­¸èˆ‡å­¸é•·å§Šï¼Œç‚ºæ ¡åœ’ç”Ÿæ´»è­œä¸‹ç¾å¥½åºæ›²å—ï¼Ÿ
        æƒ³è¦èªè­˜ä¸åŒç³»æ‰€çš„äººï¼Œè®“ç”Ÿæ´»åœˆæ›´åŠ å»£æ³›å—ï¼Ÿ
        æƒ³çŸ¥é“é¸èª²æ”»ç•¥ã€ç³»ä¸ŠçƒéšŠã€å¤šæ¨£ç¤¾åœ˜ã€æ ¡åœ’ç”Ÿæ´»ç­‰ç¬¬ä¸€æ‰‹è³‡è¨Šå—ï¼Ÿ
        é‚£å°±ä¸€å®šä¸èƒ½éŒ¯éé€™æ¬¡çš„è¿æ–°å®¿ç‡Ÿï¼",
    }
  - {
      title: "å°å¤§ç”Ÿå­˜æ”»ç•¥ï¼Ÿ",
      text:
        "é€éç²¾å¿ƒè¨­è¨ˆçš„å„ç¨®æ´»å‹•èˆ‡éŠæˆ²ï¼Œæ‹‰è¿‘å½¼æ­¤è·é›¢ï¼›åŒæ™‚è—‰ç”±å­¸é•·å§QAæ™‚é–“ï¼ŒæˆåŠŸç²å¾—å°å¤§ç”Ÿå­˜æ”»ç•¥ã€‚
        ä½ ï¼Œåƒè¬ä¸èƒ½éŒ¯éã€‚",
    }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
  - {
      count: "50",
      specialCharacter: "+",
      info: "å­¸å“¡",
      detail: "ä¾†è‡ªå…¨å°ï¼ˆä¸–ç•Œï¼Ÿï¼‰å„åœ°çš„ Elitesï¼",
    }
  - {
      count: "600",
      specialCharacter: "+",
      info: "å°æ™‚",
      detail: "å­¸é•·å§å€‘çš„ç²¾å¿ƒç­–åŠƒ",
    }
  - {
      count: "3",
      specialCharacter: "",
      info: "ç³»æ‰€",
      detail: "ä¸­æ–‡ã€è³‡ç®¡ã€å¤§æ°£ä¸‰ç³»çµ„æˆå¤šæ–¹èªè­˜ç³»ä¸Šã€å¤–ç³»æœ‹æœ‹",
    }
  - {
      count: "3",
      specialCharacter: "",
      info: "å¤©",
      detail: "è®“ä½ æ”¶ç©«æ»¿æ»¿çš„ç‡ŸéšŠ",
    }

# Latest News Block
latestNewsTitle: "æœ€æ–°æ¶ˆæ¯"

# Rockstar Speakers Block
rockstarSpeakersTitle: "åŠ å…¥æˆ‘å€‘"
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersButtonText1: "æŸ¥çœ‹æˆ‘å€‘åœ˜éšŠ"
rockstarSpeakersButtonText2: "WE ROCK æˆå“¡"

# Location Block
locationBlockTitle: "åœ°é»é€£çµ"
eventLocationName: "Conference Hall"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "22 Teatral'na St"
eventAddressLocality: "Lviv"
eventAddressLocalityRegion: "Lvivska"
eventPostalCode: "79000"
eventAddressCountry: "Ukraine"
eventStartTime: "2014-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "49.843237, 24.028751"
mapCenterCoordinates: "49.842537, 24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "å ´åœ°ä»‹ç´¹"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: '<a href="http://www.glp.com.tw">å°ä¸­æµæ˜ŸèŠ±åœ’</a>'
venueFeatures:
  [
    "<strong>åœ°å€</strong>ï¼šå°ä¸­å¸‚è±åŸå€æ°´æºè·¯åªé ‚å··8è™Ÿ",
    "<strong>é›»è©±</strong>ï¼š04-25151456",
    '<a href="http://www.glp.com.tw/camp.htm">é»æˆ‘æŸ¥çœ‹å‰å¾€è¾¦æ³•ï¼</a>',
  ]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "ä¸»è¾¦åœ˜éšŠ"
partnersTitle: "åˆä½œå¤¥ä¼´"
partnersC4sponsorsButton: "æˆ‘æƒ³è´ŠåŠ©ï¼"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "å ±åé€£çµ"
ticketsInfoTitle: "å ±åè³‡è¨Š"
ticketsInfo: "æˆ‘å€‘ç›®å‰æ¡ç”¨ç¬¬ä¸‰æ–¹å¹³å°ã€‚è‹¥å ±åä¹‹å¾Œä¸€å¤©å…§æ²’æœ‰æ”¶åˆ° Email é€šçŸ¥ï¼Œè«‹è¯ç¹«ç²‰å°ˆæˆ–ç›¸é—œæ‰¿è¾¦äººå“¡ï¼"
ticketsOffers:
  - name: "å ±åé€£çµ"
    price: "3,700 "
    priceCurrency: "NTD"
    ticketsNumber: "100"
    # ribbon: "ä¸æ­è»Š"
    featured: true
    buyButtonLink: "#"
    buyButtonText: "å ±åå°šæœªé–‹æ”¾"
    ticketContentList: []
    validFrom: "2020-07-15T00:00"
    validThrough: "2020-08-28T23:59"
    disabled: true
  - name: "å ±åé€£çµ"
    price: "4,000 "
    priceCurrency: "NTD"
    ticketsNumber: "100"
    ribbon: "æ­è»Š"
    buyButtonLink: "#"
    buyButtonText: "å ±åå°šæœªé–‹æ”¾"
    ticketContentList: []
    validFrom: "2020-07-15T00:00"
    validThrough: "2020-08-28T23:59"
    disabled: true

ticketsInfoText:
  - name: "å ±åè³‡æ ¼"
    detail: "å…¨é«”å°å¤§ä¸­æ–‡ã€å¤§æ°£åŠè³‡ç®¡ç³»å¤§ä¸€æ–°ç”Ÿ"
  - name: "æ´»å‹•åœ°é»"
    detail: "å°ä¸­æµæ˜ŸèŠ±åœ’ï¼ˆå°ä¸­å¸‚è±åŸå€æ°´æºè·¯åªé ‚å··8è™Ÿï¼‰"
  - name: "æ´»å‹•æ—¥æœŸ"
    detail: 2020ãƒ»9/11ï¼ˆäº”ï¼‰- 9/13ï¼ˆæ—¥ï¼‰
  - name: "å ±åæˆªæ­¢æ—¥æœŸ"
    detail: "2020ãƒ»8/28ï¼ˆäº”ï¼‰"
  - name: "ç‡ŸéšŠè²»ç”¨"
    detail: "æ–°å°å¹£ 3,700 å…ƒæ•´"
  - name: "æ³¨æ„äº‹é …"
    detail: "å ±åå®Œæˆå¾Œï¼Œè«‹å¡«å¦¥æ–°ç”Ÿå®¶é•·åŒæ„æ›¸æ–¼æ´»å‹•é–‹å§‹æ™‚å¸¶è‡³ç¾å ´ç¹³äº¤ã€‚è‹¥æœ‰éœ€è¦æå‰é›¢ç‡Ÿï¼Œè«‹ä¸€ä½µå¡«å¯«æå‰é›¢ç‡Ÿåˆ‡çµæ›¸ä¸”æ–¼æ´»å‹•é–‹å§‹æ™‚å¸¶è‡³ç¾å ´ç¹³äº¤"

# Footer
socialLinks:
  - { link: "#", icon: "facebook" }
  - { link: "https://github.com/icheft/2020climas", icon: "github" }

footerBlocks:
  - title: "å‹æƒ…è´ŠåŠ©"
    links:
      - { permalink: "/rockstars/", text: "WE ROCK" }
      - {
          link: "https://paypal.me/brianlxchen?locale.x=en_US",
          text: "éƒ½è¦æ²’éŒ¢äº†é‚„ä¸æ‹‰è´ŠåŠ©ï¼Œé‚£å°±ä¾†è´ŠåŠ©å‰µä½œè€…å§",
        }
      - { link: "https://ko-fi.com/icheft", text: "é€™æ˜¯å¦ä¸€å€‹è´ŠåŠ©ç®¡é“" }
      - {
          link: "https://icheft.github.io/assets/img/lineme.JPG",
          text: "ä¸ç„¶æƒå€‹ Line Pay ä¹Ÿè¡Œ",
        }
  - title: "è¯çµ¡æˆ‘å€‘"
    links:
      - { link: "tel:+886989350258", text: "è³‡è¨Šç®¡ç†å­¸ç³»çª—å£ï¼šéƒ­å­éºŸ" }
      - { link: "tel:+886910432100", text: "å¤§æ°£ç§‘å­¸ç³»çª—å£ï¼šé™¶æ˜±ä¸" }
      - { link: "tel:+886984200546", text: "ä¸­åœ‹æ–‡å­¸ç³»çª—å£ï¼šé»ƒç ”å€«" }
  - title: "å¸¸ç”¨é€£çµ"
    links:
      - { link: "https://ceiba.ntu.edu.tw/student/index.php", text: "CEIBA" }
      - { link: "https://cool.ntu.edu.tw/", text: "NTU Cool" }
      - { link: "https://pdogs.ntu.im/judge/", text: "PDOGS" }
      - { link: "https://if192.aca.ntu.edu.tw/index.php", text: "å°å¤§é¸èª²ç³»çµ±" }
      - {
          link: "https://nol.ntu.edu.tw/nol/guest/index.php",
          text: "å°å¤§èª²ç¨‹ç¶²",
        }
      - {
          link: "https://web4.cc.ntu.edu.tw/p/s/login3/p1.php",
          text: "å°å¤§å¸³è™Ÿè¨­å®š",
        }
      - {
          link: "http://www.cc.ntu.edu.tw/chinese/services/servicesqa.asp",
          text: "è¨ˆä¸­",
        }

# Blog
blogTitle: "æœ€æ–°æ¶ˆæ¯"
blogCommentsEnabled: true
discusShortName: "climas"

# Speakers List Block
showSessions: false
rockstarName: "WE ROCK"

# Team Block
teamBlockTitle: "é—œæ–¼æˆ‘å€‘"
aboutUs: "æˆ‘å€‘å°±æ˜¯ä¸€ç¾¤æºé€šä¸è‰¯çš„åœ˜éšŠã€‚ç¶²é çµ„è¦ä»€éº¼æ±è¥¿ï¼Œæˆ‘å€‘èƒ½æ‹–å°±æ‹–ã€‚æˆ‘å€‘è¶…æ£’ï¼"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
  - {
      title: "From the Airport",
      information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.',
    }
  - {
      title: "Public Transit",
      information: "Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.",
    }
  - {
      title: "Hotels",
      information: "Lviv has lots of great hotels and hostels. More information will be available later.",
    }
directionDetailsWideCards:
  - title: "Questions?"
    subCards:
      - title: "Hotels"
        links:
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "InterContinental",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "The Hotel Rex",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Westin Market Street",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Hotel Adagio",
            }
      - title: "Registration"
        links:
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "InterContinental",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "The Hotel Rex",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Westin Market Street",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Hotel Adagio",
            }
      - title: "Attendance Details"
        links:
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "InterContinental",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "The Hotel Rex",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Westin Market Street",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Hotel Adagio",
            }

downloadDetailsImage: "direction-details.jpg"
downloadDetailsTitle: "ä¸€äº›ä½ å¯èƒ½éœ€è¦çš„æ–‡ä»¶éƒ½åœ¨é€™"
downloadDetailsCards:
  - {
      title: "è¡Œå‰é€šçŸ¥æ›¸",
      information: "ä¸Šç‡Ÿå‰è«‹è¨˜å¾—è¦çœ‹ï¼å¦‚æœä½ æœ‰éœ€è¦éšŠè¼”å”åŠ©ï¼Œè«‹ä½ ä¸è¦çŒ¶è±«ï¼Œç›´æ¥è¯çµ¡ä»–å€‘ã€‚",
    }
  - {
      title: "æ–°ç”Ÿå®¶é•·åŒæ„æ›¸",
      information: 'é€™ä»½æ–‡ä»¶å¾ˆé‡è¦ï¼ä¸Šç‡Ÿä¸€å®šè¦å¸¶ï¼<a href="/assets/2020æ–°ç”Ÿå®¶é•·åŒæ„æ›¸.pdf">é»æˆ‘ä¸‹è¼‰</a>ã€‚',
    }
  - {
      title: "æå‰é›¢ç‡Ÿåˆ‡çµæ›¸",
      information: 'å¦‚æœä½ æœ‰éœ€è¦æå‰é›¢é–‹æœ¬æ¬¡ç‡ŸéšŠï¼Œè«‹ä½ å‹™å¿…å°‡æ­¤åˆ‡çµæ›¸ä¸‹è¼‰ä¸¦åˆ—å°ã€‚ç°½åå¾Œæ–¼æ´»å‹•ç•¶å¤©äº¤çµ¦éšŠè¼”ã€‚ <a href="/assets/2020ä¸­é€”é›¢ç‡Ÿåˆ‡çµæ›¸.pdf">é»æˆ‘ä¸‹è¼‰</a>ã€‚',
    }
  - {
      title: "ä¸­é€”é›¢ç‡Ÿåˆ‡çµæ›¸",
      information: 'å¦‚æœéœ€è¦ä¸­é€”é›¢ç‡Ÿï¼Œè«‹ä½ å‹™å¿…å°‡æ­¤åˆ‡çµæ›¸ä¸‹è¼‰ä¸¦åˆ—å°ã€‚ç°½åå¾Œæ–¼æ´»å‹•ç•¶å¤©äº¤çµ¦éšŠè¼”ã€‚<a href="/assets/2020ä¸­é€”é›¢ç‡Ÿåˆ‡çµæ›¸.pdf">é»æˆ‘ä¸‹è¼‰</a>ã€‚',
    }
  - {
      title: "ç‡Ÿæ‰‹å†Š",
      information: "ç‡Ÿæ‰‹å†Šä¸Šç‡Ÿæœƒç™¼ï¼Œä¸ç”¨å°ä¸‹ä¾†ï¼ä½†ä¸‹è¼‰ä¸‹ä¾†ï¼Œç•™å­˜ä¸€ä»½é›»å­æª”ï¼Œå¤šå°‘å¯ä»¥è®Šæˆå›æ†¶ ğŸ˜‰",
    }
downloadDetailsWideCards:
  - title: "Questions?"
    subCards:
      - title: "Hotels"
        links:
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "InterContinental",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "The Hotel Rex",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Westin Market Street",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Hotel Adagio",
            }
      - title: "Registration"
        links:
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "InterContinental",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "The Hotel Rex",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Westin Market Street",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Hotel Adagio",
            }
      - title: "Attendance Details"
        links:
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "InterContinental",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "The Hotel Rex",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Westin Market Street",
            }
          - {
              link: "https://plus.google.com/b/102444623953913144164",
              text: "Hotel Adagio",
            }

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
  - {
      title: "Android Wear",
      image: "hackathon-0.png",
      details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!",
    }
  - {
      title: "Google Glass",
      image: "hackathon-1.png",
      details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience.",
    }
  - {
      title: "Polymer",
      image: "hackathon-2.png",
      details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time.",
    }

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
  - { title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360" }
  - {
      title: "1nd Place",
      image: "prize-1.png",
      info: "Nexus 5 with pre-installed Android L",
    }
  - { title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast" }

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
